### ISSUE TITLE
URIs for semantic types return 404 error

### ISSUE THREAD

**Issue by osma** [HHS/meshrdf#22] opened 2015-04-02 10:13 UTC
I noticed that the URIs of semantic types give a 404 response from the server, e.g. http://id.nlm.nih.gov/mesh/T037

This is probably not the intent, but they should be serving Linked Data (or HTML for browsers).

**Comment by bushmanb** [comment] 2015-04-02 18:33
Thank you for reporting this issue.  We have discovered the cause of this problem and it will be fixed in the next beta release which is scheduled for May 2015.

**Comment by bushmanb** [comment] 2015-05-26 20:45
As an update, all semantic types will be removed from MeSH RDF with the next beta release now scheduled for June 2015.

**Closed by bushmanb** 2015-05-26 20:45 UTC
